"""empty message

Revision ID: 249a99c3c7f9
Revises: 6aa632182386
Create Date: 2023-04-22 03:20:51.262532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249a99c3c7f9'
down_revision = '6aa632182386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attributes', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('attributes')

    # ### end Alembic commands ###
