"""empty message

Revision ID: 3f97e25bb41b
Revises: 60d0e732354b
Create Date: 2023-04-21 13:02:20.972440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f97e25bb41b'
down_revision = '60d0e732354b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_web', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_i', sa.String(length=100), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_web', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('author_i')

    # ### end Alembic commands ###
