"""empty message

Revision ID: 45a986ccb50b
Revises: 2b7b8448feae
Create Date: 2023-04-26 15:29:00.271863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a986ccb50b'
down_revision = '2b7b8448feae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'website', ['website_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('website_id')

    # ### end Alembic commands ###
