"""empty message

Revision ID: 4d8b92011fb4
Revises: 86c2414fade1
Create Date: 2023-04-27 06:12:29.911617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8b92011fb4'
down_revision = '86c2414fade1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newest_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'website', ['website_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newest_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('website_id')

    # ### end Alembic commands ###
