"""empty message

Revision ID: 5e63f982d9a9
Revises: 3f97e25bb41b
Create Date: 2023-04-21 14:02:25.596768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e63f982d9a9'
down_revision = '3f97e25bb41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_to_web', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('link_to_web')

    # ### end Alembic commands ###
