"""empty message

Revision ID: 60d0e732354b
Revises: 74a53ee7374c
Create Date: 2023-04-21 13:00:37.089804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d0e732354b'
down_revision = '74a53ee7374c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('link_i', sa.String(length=1000), nullable=True),
    sa.Column('title_i', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_web')
    # ### end Alembic commands ###
