"""empty message

Revision ID: 63fa5be59012
Revises: 6092228cc420
Create Date: 2023-04-20 05:14:00.824254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fa5be59012'
down_revision = '6092228cc420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('link_p', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('middle_data', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_relate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('middle_data', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_relate')
    op.drop_table('website')
    # ### end Alembic commands ###
