"""empty message

Revision ID: 74a53ee7374c
Revises: 87c9569b754a
Create Date: 2023-04-20 12:27:32.035606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a53ee7374c'
down_revision = '87c9569b754a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_pro', sa.String(length=100), nullable=True))
        batch_op.drop_column('title_p')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_p', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('title_pro')

    # ### end Alembic commands ###
