"""empty message

Revision ID: 87c9569b754a
Revises: d7b4d77e95e1
Create Date: 2023-04-20 12:26:09.570493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c9569b754a'
down_revision = 'd7b4d77e95e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newest_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_n', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('title_n', sa.String(length=100), nullable=True))
        batch_op.drop_column('link')
        batch_op.drop_column('title_r')

    with op.batch_alter_table('promote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_pro', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('title_p', sa.String(length=100), nullable=True))
        batch_op.drop_column('link')
        batch_op.drop_column('title_r')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_r', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.drop_column('title_p')
        batch_op.drop_column('link_pro')

    with op.batch_alter_table('newest_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_r', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.drop_column('title_n')
        batch_op.drop_column('link_n')

    # ### end Alembic commands ###
