"""empty message

Revision ID: a5317d3a2652
Revises: 5e63f982d9a9
Create Date: 2023-04-21 14:02:58.625997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5317d3a2652'
down_revision = '5e63f982d9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('link_to_web')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_to_web', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
