"""empty message

Revision ID: b9e6b6ec30e5
Revises: b47f188acb92
Create Date: 2023-04-20 08:14:26.729520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e6b6ec30e5'
down_revision = 'b47f188acb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_relate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_r', sa.String(length=100), nullable=True))
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('middle_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_relate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_data', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.alter_column('link',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('title_r')

    # ### end Alembic commands ###
