"""empty message

Revision ID: be81bd2f8e22
Revises: 
Create Date: 2023-04-24 11:59:11.411140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be81bd2f8e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_tab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'website', ['website_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_tab', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('website_id')

    # ### end Alembic commands ###
